"use strict";

function esc(s) {
  return String(s == null ? "" : s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

function itemsHtml(arr) {
  if (!arr || !arr.length) return "<p class='none'>Nothing flagged.</p>";
  return arr.map((it) => `<li class="i-${esc(it.status)}"><span class="ic">${it.status === "good" ? "&#10003;" : it.status === "info" ? "i" : "!"}</span><div><b>${esc(it.label)}</b>${it.topic ? ` <span class='pill'>${esc(it.topic)}</span>` : ""}<p>${esc(it.detail)}</p></div></li>`).join("");
}

/** Build a self-contained HTML audit report for a single check. */
function buildReport(result, meta = {}) {
  const c = result.categories || {};
  const rc = result.score >= 80 ? "#1f9d6b" : result.score >= 60 ? "#d98324" : "#cf4b46";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ClearComms report</title><style>
body{font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#16323a;max-width:760px;margin:24px auto;padding:0 18px;line-height:1.5}
h1{font-size:22px;margin:0 0 2px}.sub{color:#5e7079;font-size:13px;margin:0 0 18px}
.score{display:inline-block;font-size:30px;font-weight:800;color:${rc}}
.band{color:#5e7079;font-size:14px;margin-left:8px}
h2{font-size:14px;text-transform:uppercase;letter-spacing:.5px;color:#5e7079;border-bottom:1px solid #e3eaec;padding-bottom:5px;margin:22px 0 8px}
ul{list-style:none;padding:0;margin:0}li{display:flex;gap:10px;padding:8px 0;border-bottom:1px solid #eef3f4}
.ic{flex:0 0 auto;width:20px;height:20px;border-radius:50%;color:#fff;font-size:12px;font-weight:800;display:flex;align-items:center;justify-content:center;margin-top:2px}
.i-good .ic{background:#1f9d6b}.i-warn .ic{background:#d98324}.i-issue .ic{background:#cf4b46}.i-info .ic{background:#5a7884}
li p{margin:2px 0 0;color:#5e7079;font-size:13px}.pill{font-size:10px;background:#e2f0f2;color:#0b5c68;border-radius:10px;padding:1px 7px}
.box{background:#f4f7f8;border:1px solid #dde7ea;border-radius:8px;padding:12px;white-space:pre-wrap;font-size:14px}
.meta{color:#8a9aa0;font-size:12px;margin-top:24px;border-top:1px solid #e3eaec;padding-top:10px}
.none{color:#5e7079;font-size:13px;margin:4px 0}
</style></head><body>
<h1>ClearComms check report</h1>
<p class="sub">${esc(meta.org || "")} ${meta.org ? "&middot;" : ""} ${esc(meta.date || new Date().toLocaleString("en-GB"))} &middot; ${esc(result.platform || "")} ${result.aiUsed ? "&middot; AI review" : "&middot; rules check"}</p>
<p><span class="score">${esc(result.score)}</span><span class="band">/100 &middot; ${esc(result.band)} &middot; reading age about ${esc(result.readingAge)}</span></p>
${result.summary ? `<p>${esc(result.summary)}</p>` : ""}
<h2>Inclusive language</h2><ul>${itemsHtml(c.inclusive)}</ul>
<h2>Clarity and plain English</h2><ul>${itemsHtml(c.clarity)}</ul>
<h2>Accessibility</h2><ul>${itemsHtml(c.accessibility)}</ul>
<h2>Tone and platform</h2><ul>${itemsHtml(c.tone)}</ul>
<h2>Original</h2><div class="box">${esc(meta.input || "")}</div>
<h2>Suggested rewrite</h2><div class="box">${esc(result.rewrite || "")}</div>
<p class="meta">Generated by ClearComms. Assistive only: keep a human in the loop before publishing.</p>
</body></html>`;
}

module.exports = { buildReport, esc };
